import Config from 'react-native-config';

export default {
	API_URL: Config.API_URL,
	BACK_URL: Config.BACK_URL,
	FRONT_URL: Config.FRONT_URL,
	TELADOC_URL: Config.TELADOC_URL,
	SYMPTOM_CHECKER: {
		THEME: Config.SYMPTOM_CHECKER_THEME,
		LAN: {
			EN: {
				USER: Config.SYMPTOM_CHECKER_USER_EN,
				PASS: Config.SYMPTOM_CHECKER_PASS_EN,
				PROC_ID: Config.SYMPTOM_CHECKER_PROC_ID_EN,
			},
			ES: {
				USER: Config.SYMPTOM_CHECKER_USER_ES,
				PASS: Config.SYMPTOM_CHECKER_PASS_ES,
				PROC_ID: Config.SYMPTOM_CHECKER_PROC_ID_ES,
			},
		},
	},
	LIFESTYLE_LIB: {
		THEME: Config.LIFESTYLE_LIB_THEME,
		ENV: Config.LIFESTYLE_LIB_ENV,
		LAN: {
			EN: {
				USER: Config.LIFESTYLE_LIB_USER_EN,
				PASS: Config.LIFESTYLE_LIB_PASS_EN,
				PROC_ID: Config.LIFESTYLE_LIB_PROC_ID_EN,
			},
			ES: {
				USER: Config.LIFESTYLE_LIB_USER_ES,
				PASS: Config.LIFESTYLE_LIB_PASS_ES,
				PROC_ID: Config.LIFESTYLE_LIB_PROC_ID_ES,
			},
		},
		DIALOG_FLOW: {
			dlgflowRegion: Config.DIALOG_FLOW_REGION,
			dlgflowProject: Config.DIALOG_FLOW_PROJECT,
			dlgflowEnv: Config.DIALOG_FLOW_ENV,
			dlgflowSymptomAgentID: Config.DIALOG_FLOW_SYMPTOM_AGENT_ID,
		},
	},
	VIRTUAL_ASSISTANT: {
		THEME: Config.VIRTUAL_ASSISTANT_THEME,
		ENV: Config.VIRTUAL_ASSISTANT_ENV,
		LAN: {
			EN: {
				USER: Config.VIRTUAL_ASSISTANT_USER_EN,
				PASS: Config.VIRTUAL_ASSISTANT_PASS_EN,
				PROC_ID: Config.VIRTUAL_ASSISTANT_PROC_ID_EN,
			},
			ES: {
				USER: Config.VIRTUAL_ASSISTANT_USER_ES,
				PASS: Config.VIRTUAL_ASSISTANT_PASS_ES,
				PROC_ID: Config.VIRTUAL_ASSISTANT_PROC_ID_ES,
			},
		},
		DIALOG_FLOW: {
			dlgflowRegion: Config.DIALOG_FLOW_REGION,
			dlgflowProject: Config.DIALOG_FLOW_PROJECT,
			dlgflowEnv: Config.DIALOG_FLOW_ENV,
			dlgflowSymptomAgentID: Config.DIALOG_FLOW_SYMPTOM_AGENT_ID,
		},
	},
	PUBLIC_VERSION_USER: Config.PUBLIC_VERSION_USER,
	PUBLIC_VERSION_PSSWRD: Config.PUBLIC_VERSION_PSSWRD,
	PUBLIC_API_TOKEN: Config.PUBLIC_API_TOKEN,
	INTERCOM_APP_ID: Config.INTERCOM_APP_ID,
	VIM_API_KEY: Config.VIM_API_KEY,
	VIM_ENVIRONMENT: Config.VIM_ENVIRONMENT,
	FB_INSURANCE_URL: Config.FB_INSURANCE_URL,
	FB_INSURANCE_URL_ANDROID: Config.FB_INSURANCE_URL_ANDROID,
	FB_INSURANCE_URL_IOS: Config.FB_INSURANCE_URL_IOS,
	CAPTCHA_V3_KEY: Config.CAPTCHA_V3_KEY,
	CALL_NUMBER: Config.CALL_NUMBER,
	HEALTH: {
		THEME: Config.HEALTH_THEME,
		EN: {
			USER_NAME: Config.HEALTH_USER_NAME_EN,
			PASSWORD: Config.HEALTH_PASSWORD_EN,
			PROCEDURE_ID: Config.HEALTH_PROCEDURE_ID_EN,
		},
		ES: {
			USER_NAME: Config.HEALTH_USER_NAME_ES,
			PASSWORD: Config.HEALTH_PASSWORD_ES,
			PROCEDURE_ID: Config.HEALTH_PROCEDURE_ID_ES,
		},
	},
	AVAILITY_URL: Config.AVAILITY_URL,
	PUBLISHABLEKEY_PAYMENT: Config.PUBLISHABLEKEY_PAYMENT,
};
