export enum ASYNC_STORAGE {
	ONBOARDING = 'ONBOARDING',
	LANGUAGE = 'LANGUAGE',
	NEW_VISIT = 'NEW_VISIT_MODAL',
	MODAL = 'MODAL',
	CAPTCHA = 'grecaptchatoken',
	CHECK = 'CHECK',
	BIOMETRICALUSER = 'USERBIOMETRICAL',
	BIOMETRICALOPTION = 'BIOMETRICALOPTION',
	BIOMETRICALMODAL = 'BIOMETRICALMODAL',
	BIOMETRICALTERMS = 'BIOMETRICALTERMS'

}

export enum ONBOARDING_VALUES {
	SHOWN = 'SHOWN',
	NOT_SHOWN = 'NOT_SHOWN',
}

export default {
	FEATURE_NOTIFICATION: false,
	FEATURE_ENROLLDEVICE: false,
  };
